-- UTILIZO MI BASE DE DATOS
use proyecto2;

-- LUEGO SE EJECUTA EL SIGUIENTE COMANDOS EN MYSQL
LOAD DATA LOCAL INFILE 'C:\\Users\\Chay\\Downloads\\pruebaTXT.csvC:\Users\diego\OneDrive\Documentos\Bases_1\Laboratorio\BD_Proyecto_2\carga.csv' 
INTO TABLE proyecto2.temporal COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\r\n' -- LINUX  '\n' 
IGNORE 1 LINES (NOMBRE_ELECCION,ANIO_ELECCION,PAIS,REGION,DEPTO,MUNICIPIO,PARTIDO,NOMBRE_PARTIDO,SEXO,RAZA,ANALFABETOS,ALFABETOS,PRIMARIA,NIVEL_MEDIO,UNIVERSITARIOS);
